# ----------------------------
# Makefile Options
# ----------------------------

NAME = CXSOLVE
DESCRIPTION = "Complex System Solver"
COMPRESSED = NO
ARCHIVED = YES

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

LIBS = libload.lib

# ----------------------------

include $(CEDEV)/meta/makefile.mk